server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5331/customer
    username: alexey
    password: password
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
