server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://localhost:5332/fraud
    username: alexey
    password: password
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 0.5